// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_chamados.src.Infrastructure.Data.Context;

#nullable disable

namespace Sistema_de_chamados.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616014101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Acompanhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChamadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAcompanhamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Acompanhamentos");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChamadosEmAberto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAssociacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Acompanhamento", b =>
                {
                    b.HasOne("Sistema_de_chamados.src.Domain.Entities.Chamado", "Chamado")
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_de_chamados.src.Domain.Entities.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Chamado", b =>
                {
                    b.HasOne("Sistema_de_chamados.src.Domain.Entities.Responsavel", "Responsavel")
                        .WithMany("ChamadosAtribuidos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sistema_de_chamados.src.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ChamadosAbertos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Responsavel", b =>
                {
                    b.HasOne("Sistema_de_chamados.src.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ResponsaveisAssociados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Chamado", b =>
                {
                    b.Navigation("Acompanhamentos");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Responsavel", b =>
                {
                    b.Navigation("ChamadosAtribuidos");
                });

            modelBuilder.Entity("Sistema_de_chamados.src.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ChamadosAbertos");

                    b.Navigation("ResponsaveisAssociados");
                });
#pragma warning restore 612, 618
        }
    }
}
